import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "flex-end",
  },
  box: {
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  inner: {
    position: "relative",
    marginTop: "auto",
    paddingTop: 32,
    paddingHorizontal: 16,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    backgroundColor: "#FFFFFF",
  },
  avatar: {
    position: "absolute",
    top: "0",
    left: "50%",
    transform: [{ translateX: -44 }, { translateY: -60 }],
    margin: "auto",
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
  },
  buttonAdd: {
    position: "absolute",
    top: "0",
    left: "0",
    transform: [{ translateX: 107.5 }, { translateY: 81 }],
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderRadius: 50,
    borderColor: "#FF6C00",
  },
  buttonClose: {
    position: "absolute",
    top: "0",
    left: "0",
    transform: [{ translateX: 107.5 }, { translateY: 81 }, { rotate: "45deg" }],
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8E8E8",
    borderWidth: 1,
    borderRadius: 50,
    borderColor: "#BDBDBD",
  },
  text: {
    marginTop: 92,
    marginBottom: 32,
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    lineHeight: 35.16,
    color: "#212121",
    textAlign: "center",
  },
  form: {
    display: "flex",
  },
  inputContainer: {
    position: "relative",
    display: "flex",
    gap: 16,
    marginBottom: 43,
  },
  input: {
    display: "flex",
    width: "100%",
    height: 50,
    padding: 16,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#E8E8E8",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 18.75,
    color: "#212121",
  },
  inputOnFocus: {
    borderColor: "#FF6C00",
    backgroundColor: "#fff",
  },
  showBtnText: {
    position: "absolute",
    bottom: 0,
    right: 0,
    transform: [{ translateX: -16 }, { translateY: -32 }],
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 18.75,
    color: "#1B4371",
  },
  signInBtn: {
    marginBottom: 45,
    alignItems: "center",
  },

  signInBtnLink: {
    textDecorationLine: "underline",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 18.75,
    color: "#1B4371",
    textAlign: "center",
  },
  submitBtn: {
    width: "100%",
    height: 51,
    marginBottom: 16,
    paddingHorizontal: 32,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
    backgroundColor: "#FF6C00",
  },
  submitText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 18.75,
    color: "#fff",
    textAlign: "center",
  },
});
